Repository Xahau/xahaud, pull requests merged in 2024-03, with the labels that each got.

#278 Amendment: `featureRemit`
  Builds/CMake/RippledCore.cmake
  hook/tts.h
  src/ripple/app/hook/impl/applyHook.cpp
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/Remit.cpp
  src/ripple/app/tx/impl/Remit.h
  src/ripple/app/tx/impl/SetAccount.cpp
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/LedgerFormats.h
  src/ripple/protocol/SField.h
  src/ripple/protocol/TxFlags.h
  src/ripple/protocol/TxFormats.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/InnerObjectFormats.cpp
  src/ripple/protocol/impl/SField.cpp
  src/ripple/protocol/impl/TxFormats.cpp
  src/ripple/protocol/jss.h
  src/ripple/rpc/handlers/AccountInfo.cpp
  src/test/app/Remit_test.cpp
  src/test/app/SetHookTSH_test.cpp
  src/test/jtx.h
  src/test/jtx/impl/remit.cpp
  src/test/jtx/remit.h
  src/test/rpc/AccountInfo_test.cpp
  src/test/rpc/AccountSet_test.cpp
  src/test/rpc/AccountTx_test.cpp
Labels: Amendment

#293 ZeroB2M amendment
  src/ripple/app/tx/impl/Import.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/impl/Feature.cpp
  src/test/app/Import_test.cpp
Labels: Amendment, feature

#296 Fix: Namespace Delete (OwnerCount)
  src/ripple/app/hook/Enum.h
  src/ripple/app/hook/impl/applyHook.cpp
  src/ripple/app/misc/NetworkOPs.cpp
  src/ripple/app/misc/impl/TxQ.cpp
  src/ripple/app/paths/Flow.cpp
  src/ripple/app/paths/PathRequest.cpp
  src/ripple/app/paths/Pathfinder.cpp
  src/ripple/app/paths/impl/BookStep.cpp
  src/ripple/app/paths/impl/DirectStep.cpp
  src/ripple/app/paths/impl/PaySteps.cpp
  src/ripple/app/paths/impl/XRPEndpointStep.cpp
  src/ripple/app/tx/applySteps.h
  src/ripple/app/tx/impl/CashCheck.cpp
  src/ripple/app/tx/impl/CreateOffer.cpp
  src/ripple/app/tx/impl/Escrow.cpp
  src/ripple/app/tx/impl/Import.cpp
  src/ripple/app/tx/impl/InvariantCheck.cpp
  src/ripple/app/tx/impl/NFTokenAcceptOffer.cpp
  src/ripple/app/tx/impl/NFTokenMint.cpp
  src/ripple/app/tx/impl/Payment.cpp
  src/ripple/app/tx/impl/Remit.cpp
  src/ripple/app/tx/impl/SetHook.cpp
  src/ripple/app/tx/impl/SetSignerList.cpp
  src/ripple/app/tx/impl/SignerEntries.cpp
  src/ripple/app/tx/impl/Taker.cpp
  src/ripple/app/tx/impl/Transactor.cpp
  src/ripple/app/tx/impl/URIToken.cpp
  src/ripple/app/tx/impl/applySteps.cpp
  src/ripple/ledger/impl/View.cpp
  src/ripple/protocol/Feature.h
  src/ripple/protocol/TER.h
  src/ripple/protocol/impl/Feature.cpp
  src/ripple/protocol/impl/TER.cpp
  src/ripple/rpc/impl/DeliveredAmount.cpp
  src/test/app/SetHook_test.cpp
Labels: fix, Amendment
